[build]
  publish = "public"
  command = "npm build"
[build.environment]
  npm_VERSION = "1.3.2"
  npm_FLAGS = "--no-ignore-optional"




// swipe left  - ARCHIVE , MARK AS SPAM
// SWIPR RIGHT - UNDO AND MARK UNREAD